#Project: Wonderly backend
#Created by: David Ramirez
#Date: 10/17/18
#Copyright 2018 LeapWithAlice,LLC. All rights reserved

runtime: python27
threadsafe: true

# Handlers tell App Engine how to route requests to your application.
handlers:

# The following three handlers route requests to static resources: JS, CSS,
# and HTML.
- url: /static
  static_dir: static
- url: /
  static_files: static/index.html
  upload: static/index\.html
  secure: always

# This handler routes requests to your APIs to your Endpoints code.
# See https://developers.google.com/appengine/docs/python/endpoints/
- url: /_ah/api/.*
  script: wonderly.api
  secure: always


# Third party libraries that are included in the App Engine SDK must be listed
# here if you want to use them. See
# https://developers.google.com/appengine/docs/python/tools/libraries27 for
# a list of libraries included in the SDK. Third party libs that are *not* part
# of the App Engine SDK don't need to be listed here, instead add them to your
# project directory, either as a git submodule or as a plain subdirectory.
# Note that dependencies must be located in your project directory - packages
# installed in the Python environment are not loaded by the App Engine
# development server or deployment tools.
# TODO: List any other App Engine SDK libs you may need here.
libraries:

# You must include the Endpoints library if you wish to serve an API.
#- name: endpoints
#  version: latest

- name: webapp2
  version: latest

- name: pycrypto
  version: latest

- name: ssl
  version: latest


env_variables:
  # The following values are to be replaced by information from the output of
  # 'gcloud endpoints services deploy swagger.json' command.
  ENDPOINTS_SERVICE_NAME: wonderly-225214.appspot.com

  ENDPOINTS_SERVICE_VERSION: 2018-12-12r0




